@extends('layouts.admin')
@section('title','Quản lý Tags')
@section('breadcrumb','Tags')
@section('topbar-actions')<a href="#quick-create" class="topbar-btn topbar-btn-primary">🏷️ Thêm Tag</a>@endsection

@section('content')
<div class="admin-page-header"><h1 class="admin-page-title">🏷️ Quản lý Tags</h1><p class="admin-page-sub">Tên, slug, màu và số truyện liên kết đều lấy từ database. Không còn toggle trạng thái giả.</p></div>
<div class="dashboard-grid">
  <div class="col-main-8" style="display:flex;flex-direction:column;gap:16px">
    <div class="admin-card" style="padding:16px;margin-bottom:0"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap"><input id="search-tag" class="form-control" style="max-width:390px" placeholder="🔍 Tìm tag theo tên hoặc slug..."><span style="font-size:12px;color:var(--admin-text-muted)">Tổng: <strong>{{ $tags->total() }}</strong></span></div></div>
    <div class="admin-card" style="margin-bottom:0"><form method="POST" action="{{ route('admin.tags.bulkDestroy') }}" id="tag-bulk-form">@csrf @method('DELETE')<div class="admin-card-header"><span class="admin-card-title">Danh sách Tags</span><button id="tag-bulk-delete" class="btn-admin btn-admin-danger btn-sm" disabled>🗑️ Xóa đã chọn</button></div>
      @if($tags->isEmpty())<div style="text-align:center;padding:48px;color:var(--admin-text-muted)">🏷️ Chưa có tag nào.</div>@else<div style="overflow-x:auto"><table class="admin-table"><thead><tr><th style="width:36px"><input type="checkbox" id="tag-check-all"></th><th>Tag</th><th>Slug</th><th>Màu</th><th style="text-align:center">Số truyện</th><th style="text-align:center">Thao tác</th></tr></thead><tbody>
        @foreach($tags as $tag)<tr class="tag-row"><td><input type="checkbox" class="tag-check" name="ids[]" value="{{ $tag->id }}"></td><td><span style="display:inline-block;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:800;background:{{ $tag->color ? $tag->color.'22':'rgba(255,255,255,.07)' }};color:{{ $tag->color ?: 'var(--admin-text)' }};border:1px solid {{ $tag->color ? $tag->color.'55':'var(--admin-border)' }}">{{ $tag->name }}</span></td><td><code>{{ $tag->slug }}</code></td><td>@if($tag->color)<span class="color-swatch" style="background:{{ $tag->color }}"></span><code>{{ $tag->color }}</code>@else—@endif</td><td style="text-align:center"><span class="badge badge-primary">{{ number_format($tag->comics_count) }}</span></td><td><div style="display:flex;justify-content:center;gap:6px"><a href="{{ route('admin.tags.edit',$tag) }}" class="btn-admin btn-admin-ghost btn-sm">✏️ Sửa</a><button type="button" class="btn-admin btn-admin-danger btn-sm" onclick="confirmDelete('{{ route('admin.tags.destroy',$tag) }}','Tag: {{ addslashes($tag->name) }}')">🗑️</button></div></td></tr>@endforeach
      </tbody></table></div><div class="pagination-wrap">{{ $tags->links() }}</div>@endif</form></div>
  </div>
  <aside class="col-sidebar-4" id="quick-create"><div class="admin-card" style="position:sticky;top:80px"><div class="admin-card-header"><span class="admin-card-title">🏷️ Thêm Tag</span></div><form action="{{ route('admin.tags.store') }}" method="POST">@csrf<div class="form-group"><label class="form-label">Tên Tag <span>*</span></label><input class="form-control" name="name" id="tag-name" required value="{{ old('name') }}"></div><div class="form-group"><label class="form-label">Slug</label><input class="form-control" name="slug" value="{{ old('slug') }}" placeholder="Để trống sẽ tự tạo"></div><div class="form-group"><label class="form-label">Màu</label><div style="display:flex;gap:8px"><input type="color" id="tag-color-picker" value="{{ old('color','#6c63ff') }}" style="width:48px;height:40px"><input class="form-control" name="color" id="tag-color" value="{{ old('color','#6c63ff') }}"></div><div id="tag-preview" style="margin-top:8px;display:inline-block;padding:5px 12px;border-radius:999px;font-size:12px;font-weight:800">Preview</div></div><button class="btn-admin btn-admin-primary" style="width:100%;justify-content:center">💾 Lưu Tag</button></form></div></aside>
</div>
@endsection

@push('scripts')
<script>
(() => { const search=document.getElementById('search-tag'),rows=[...document.querySelectorAll('.tag-row')],checks=[...document.querySelectorAll('.tag-check')],all=document.getElementById('tag-check-all'),bulk=document.getElementById('tag-bulk-delete'),picker=document.getElementById('tag-color-picker'),hex=document.getElementById('tag-color'),preview=document.getElementById('tag-preview'),name=document.getElementById('tag-name');search?.addEventListener('input',()=>{const q=search.value.toLowerCase();rows.forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'':'none')});const sync=()=>{const n=checks.filter(c=>c.checked).length;bulk.disabled=n===0;if(all)all.checked=n>0&&n===checks.length};checks.forEach(c=>c.addEventListener('change',sync));all?.addEventListener('change',()=>{checks.forEach(c=>c.checked=all.checked);sync()});document.getElementById('tag-bulk-form')?.addEventListener('submit',e=>{const n=checks.filter(c=>c.checked).length;if(!n||!confirm(`Xóa ${n} tag đã chọn? Tag đang gán cho truyện sẽ được bỏ qua.`))e.preventDefault()});const paint=()=>{const c=/^#[0-9a-f]{6}$/i.test(hex.value)?hex.value:'#6c63ff';preview.style.background=c+'22';preview.style.color=c;preview.style.border=`1px solid ${c}55`;preview.textContent=name.value||'Preview'};picker?.addEventListener('input',()=>{hex.value=picker.value;paint()});hex?.addEventListener('input',()=>{if(/^#[0-9a-f]{6}$/i.test(hex.value))picker.value=hex.value;paint()});name?.addEventListener('input',paint);paint(); })();
</script>
@endpush
